article/urls.py
from django.urls import path
from . import views

app_name = 'article'

urlpatterns = [
    path('article-list/', views.article_list, name='article_list'),
    path('article-detail/<int:id>/', views.article_detail, name='article_detail'),
    path('article-create/', views.article_create, name='article_create'),
    path('article-delete/<int:id>/', views.article_delete, name='article_delete'),
    path('article-update/<int:id>/',views.article_update,name = 'article_update')
]

comment/urls.py
from django.urls import path
from . import views

app_name = 'comment'

urlpatterns = [
    # 发表评论,处理一级回复
    path('post-comment/<int:article_id>/',views.post_comment,name='post_comment'),
    # 处理二级回复
    path('post-comment/<int:article_id>/<int:parent_comment_id>',views.post_comment,name='comment_reply')

]

my_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

import notifications.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('article/', include('article.urls', namespace='article')),
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    path('password-reset/', include('password_reset.urls')),
    path('comment/',include('comment.urls',namespace='comment')),
    path('inbox/notifications/',include(notifications.urls,namespace='notifications')),
    path('notice/',include('notice.urls',namespace='notice')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notice/urls.py
from django.urls import path
from . import views

app_name = 'notice'

urlpatterns = [
    # 通知列表
    path('list/',views.CommentNoticeListView.as_view(),name='list'),
    # 更新通知状态
    path('update/',views.CommentNoticeUpdateView.as_view(),name='update'),
]

userprofile/urls.py
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [
    # 用户登录
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.user_register, name='register'),
    path('delete/<int:id>/', views.user_delete, name='delete'),
    path('edit/<int:id>/',views.profile_edit,name='edit'),
]

article/models.py
from django.db import models
# 导入内建的User模型
from django.contrib.auth.models import User
# timezone用来处理时间相关的事务
from django.utils import timezone
from django.urls import reverse
# 引入标签
from taggit.managers import TaggableManager
from PIL import Image


# Create your models here.

class ArticleColumn(models.Model):
    """栏目的model"""
    title = models.CharField(max_length=100, blank=True,verbose_name="名称")
    created = models.DateTimeField(default=timezone.now,verbose_name="创建时间")

    def __str__(self):
        return self.title
    class Meta:
        verbose_name = verbose_name_plural = "文章分类"



# 博客文章数据模型
class ArticlePost(models.Model):
    # 文章作者，指定on_delete删除方式
    author = models.ForeignKey(User, on_delete=models.CASCADE,verbose_name="作者")

    # models.CharField 为字符串字段，用于保存较短的字符串，如标题。
    title = models.CharField(max_length=100,verbose_name="标题")

    # 文章正文，保存大量文本使用，TextField
    body = models.TextField(verbose_name="正文")

    # 文章创建时间。参数 default=timezone.now指定其创建数据时将默认写入当前时间。
    created = models.DateTimeField(default=timezone.now,verbose_name="创建时间")

    # 文章更新，参数 auto_now = true 指定每次数据更新时自动写入当前时间
    updated = models.DateTimeField(auto_now=True,verbose_name="更新时间")

    # 统计浏览量
    total_views = models.PositiveIntegerField(default=0,verbose_name="浏览量")

    # 文章标签
    tags = TaggableManager(blank=True,verbose_name="文章标签")

    # 文章标题图
    avatar = models.ImageField(upload_to='article/%Y%m%d', blank=True,verbose_name="文章标题图")

    # 文章栏目的“一对多”外键
    column = models.ForeignKey(
        ArticleColumn,
        null=True,
        blank=True,
        on_delete=models.CASCADE,
        related_name='article',
        verbose_name="类别",
    )

    # 保存时处理图片
    def save(self, *args, **kwargs):
        # 调用原有的save()的功能
        article = super(ArticlePost, self).save(*args, **kwargs)
        # 固定宽度缩放图片大小
        if self.avatar and not kwargs.get('update_fields'):
            image = Image.open(self.avatar)
            (x, y) = image.size
            new_x = 400
            new_y = int(new_x * (y / x))
            resized_image = image.resize((new_x, new_y), Image.ANTIALIAS)
            resized_image.save(self.avatar.path)
        return article

    # 内部类 class Meta用于给 model定义元数据
    class Meta:
        # 指定模型返回的数据的排列顺序
        # ‘-created’表明数据应该以倒序排列
        ordering = ('-created',)
        verbose_name_plural = verbose_name = "文章"

    # 函数 __str__定义当调用对象的str()方法时返回的值
    def __str__(self):
        return self.title

    # 获取文章地址
    def get_absolute_url(self):
        return reverse('article:article_detail', args=[self.id])

article/forms.py
# 引入表单类
from django import forms
# 引入文章模型
from .models import ArticlePost


# 写文章的表单类
class ArticlePostForm(forms.ModelForm):
    class Meta:
        # 指明数据模型来源
        model = ArticlePost
        # 定义表单包含的字段
        fields = ('title', 'body', 'tags', 'avatar')

article/views.py
import markdown
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.models import User
# 导入数据模型
from .models import ArticlePost, ArticleColumn
from .forms import ArticlePostForm
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Q
from comment.models import Comment
from comment.forms import CommentForm


# Create your views here.

# 视图函数
def article_list(request):
    search = request.GET.get('search')
    order = request.GET.get('order')
    column = request.GET.get('column')
    tag = request.GET.get('tag')

    # 初始化查询集
    article_list = ArticlePost.objects.all()

    # 搜索查询集
    if search:
        article_list = article_list.filter(
            Q(title__icontains=search) |
            Q(body__icontains=search)
        )
    else:
        search = ''

    # 栏目查询集
    if column is not None and column.isdigit():
        article_list = article_list.filter(column=column)

    # 标签查询集
    if tag and tag != 'None':
        article_list = article_list.filter(tags__name__in=[tag])

    # 查询集排序
    if order == 'total_views':
        article_list = article_list.order_by('-total_views')

    # 每页显示3篇文章
    paginator = Paginator(article_list, 3)
    # 获取url中的页码
    page = request.GET.get('page')
    # 将导航对象相应的页码内容返回给articles
    articles = paginator.get_page(page)
    # 需要传递给模板的对象
    context = {'articles': articles, 'order': order, 'search': search, 'column': column, 'tag': tag}
    # render函数：载入模板，并返回context对象
    return render(request, 'article/list.html', context)


def article_detail(request, id):
    # 取出响应文章
    article = ArticlePost.objects.get(id=id)
    # 取出文章的评论[filter()可以取出满足条件的多个对象，get()只能取一个]
    comments = Comment.objects.filter(article=id)

    # 浏览量+1
    article.total_views += 1
    article.save(update_fields=['total_views'])
    # 将markdown语法渲染成html样式
    md = markdown.Markdown(
        extensions=[
            # 包含 缩写、表格等常用扩展
            'markdown.extensions.extra',
            # 语法高亮扩展
            'markdown.extensions.codehilite',
            # 目录拓展
            'markdown.extensions.toc',
        ])
    article.body = md.convert(article.body)
    # 引入评论表单
    comment_form = CommentForm()
    # 需要传递给模板对象,新增md.toc对象
    context = {'article': article,
               'toc': md.toc,
               'comments': comments,
               'comment_form': comment_form,
               }
    return render(request, 'article/detail.html', context)


# 写文章的视图
@login_required(login_url='/userprofile/login/')
def article_create(request):
    # 判断用户是否提交数据
    if request.method == "POST":
        # 将提交的数据赋值到表单实例中
        article_post_form = ArticlePostForm(request.POST, request.FILES)
        # 判断提交的数据是否满足模型的要求
        if article_post_form.is_valid():
            # 保存数据，但暂时不提交到数据库中
            new_article = article_post_form.save(commit=False)
            # 指定数据库中 id=1 的用户为作者
            # 如果你进行过删除数据表的操作，可能会找不到id=1的用户
            # 此时请重新创建用户，并传入此用户的id
            new_article.author = User.objects.get(id=request.user.id)
            if request.POST['column'] != 'none':
                new_article.column = ArticleColumn.objects.get(id=request.POST['column'])
            # 将文章保存到数据库中
            new_article.save()
            # 保存tags的多对多关系
            article_post_form.save_m2m()
            # 完成后返回到文章列表
            return redirect('article:article_list')
        else:
            return HttpResponse("表单内容有误，请重新填写。")
    # 如果用户请求获取数据
    else:
        # 创建表单类实例
        article_post_form = ArticlePostForm()
        columns = ArticleColumn.objects.all()
        # 赋值上下文
        context = {'article_post_from': article_post_form, 'columns': columns}
        # 返回模板
        return render(request, 'article/create.html', context)


# 删除文章
@login_required(login_url='/userprofile/login/')
def article_delete(request, id):
    # 根据id获取要删除的文章
    article = ArticlePost.objects.get(id=id)
    if request.user != article.author:
        return HttpResponse("抱歉，你没有权限修改这篇文章")
    # 调用 delete()方法删除文章
    article.delete()
    # 删除后返回文章列表
    return redirect('article:article_list')


# 更新文章
@login_required(login_url='/userprofile/login/')
def article_update(request, id):
    """
    更新文章的视图函数
    通过POST方式提交表单，更新title、body字段
    GET方法进入初始表单页
    """
    # 获取需要修改的具体文章对象
    article = ArticlePost.objects.get(id=id)
    # 验证是否为作者本人
    if request.user != article.author:
        return HttpResponse("抱歉，你没有权限修改这篇文章！")
    if request.method == 'POST':
        # 将提交的数据赋值到表单实例中
        article_post_form = ArticlePostForm(data=request.POST)
        # 判断提交的数据是否满足模型要求
        if article_post_form.is_valid():
            # 保存新写入的title、body数据并保存
            article.title = request.POST['title']
            article.body = request.POST['body']
            if request.POST['column'] != 'none':
                article.column = ArticleColumn.objects.get(id=request.POST['column'])
            else:
                article.column = None
            if request.FILES.get('avatar'):
                article.avatar = request.FILES.get('avatar')
            article.tags.set(*request.POST.get('tags').split(','), clear=True)
            article.save()
            # 完成后返回到修改后的文章中。需要传入文章的id值
            return redirect('article:article_detail', id=id)
        else:
            return HttpResponse("表单内容有误，请重新填写")
    # 如果是GET请求获取数据
    else:
        # 创建表单类实例
        article_post_form = ArticlePostForm()
        columns = ArticleColumn.objects.all()

        # 赋值上下文
        context = {'article': article,
                   'article_post_form': article_post_form,
                   'columns': columns,
                   'tags': '.'.join([x for x in article.tags.names()]),
                   }
        # 将响应返回到模板中
        return render(request, 'article/update.html', context)

templates/article/create.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}

{% endblock %}

{% block content %}
    <!-- 写文章表单-->
    <div class="container">
        <div class="row">
            <div class="col-12">
                <br>
                <!-- 提交文章表单-->
                <form method="post" action="." enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="title">文章标题</label>
                        <input type="text" class="form-control" id="title" name="title">
                    </div>

                    <div class="form-group">
                        <label for="avatar">标题图</label>
                        <input type="file" class="form-control-file" name="avatar" id="avatar">
                    </div>

                    <div class="form-group">
                        <label for="column">栏目</label>
                        <select class="form-control col-3" id="column" name="column">
                            <option value="none">请选择栏目</option>
                            {% for column in columns %}
                                <option value="{{ column.id }}">{{ column }}</option>
                            {% endfor %}
                        </select>
                    </div>

                    <div class="form-group">
                        <label for="tags">标签</label>
                        <input type="text" class="form-control col-3" id="tags" name="tags">
                    </div>

                    <div class="form-group">
                        <label for="body">文章正文</label>
                        <textarea for="text" class="form-control" id="body" name="body" rows="12"></textarea>
                    </div>

                    <button type="submit" class="btn btn-primary">完成</button>
                </form>
            </div>
        </div>
    </div>


{% endblock content %}

templates/article/detail.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %}
{% load staticfiles %}

<!-- 写入 base.html 中定义的 title -->
{% block title %}
文章详情
{% endblock title %}

<!-- 写入 base.html 中定义的 content -->
{% block content %}
<script src="{% static 'ckeditor/ckeditor/plugins/prism/lib/prism/prism_patched.min.js' %}"></script>
<link rel="stylesheet" href="{% static 'prism/prism.css' %}">

<!-- 文章详情 -->
<div class="container">
    <div class="row">
        <div class="col-9">
            <!-- 标题及作者 -->
            <h1 class="mt-4 mb-4">{{ article.title }}</h1>
            <div class="alert alert-success">
                <div>
                    作者：{{ article.author }}
                    {% if user == article.author %}

                        <!-- · <a href="#" onclick="confirm_delete()">删除文章</a> -->
                        · <a href="#" onclick="confirm_safe_delete()">删除文章</a>
                        <form
                            style="display:none;"
                            id="safe_delete"
                            action="{% url 'article:article_delete' article.id %}"
                            method="POST"
                        >
                        {% csrf_token %}
                            <button type="submit">发送</button>
                        </form>

                        · <a href="{% url "article:article_update" article.id %}">
                            编辑文章
                        </a>
                    {% endif %}
                </div>
                <div>
                    浏览：{{ article.total_views }}
                </div>
            </div>
            <!-- 文章正文 -->
            <div class="col-12">
                <p>{{ article.body|safe }}</p>
            </div>

            <!-- 点赞 -->
{#            <div style="text-align:center;" class="mt-4">#}
{#                <button class="btn btn-outline-danger"#}
{#                        type="button"#}
{#                        onclick="validate_is_like(#}
{#                                '{% url 'article:increase_likes' article.id %}',#}
{#                                {{ article.id }},#}
{#                                {{ article.likes }}#}
{#                            )"#}
{#                >#}
{#                    <span>点赞</span>#}
{#                    <span>#}
{#                        <i class="fas fa-heart"></i>#}
{#                    </span>#}
{#                    <span id="likes_number">#}
{#                        {{ article.likes }}#}
{#                    </span>#}
{#                </button>#}
{#            </div>#}

            <!-- 相邻文章导航 -->
            <br>
            <div class="row justify-content-end">
                {% if next_article %}
                <div class="col-auto mr-auto">
                    <a  href="{{ next_article.get_absolute_url }}"
                        class="btn btn-info"
                        >
                        {{ next_article.title }}
                    </a>
                </div>
                {% endif %}
            {% if pre_article %}
                <div class="col-auto">
                    <a  href="{{ pre_article.get_absolute_url }}"
                    class="btn btn-info"
                    >
                        {{ pre_article.title }}
                    </a>
                </div>
            {% endif %}
            </div>


            <!-- 发表评论 -->
            <hr>
            {% if user.is_authenticated %}
                <div>
                    <form
                        action="{% url 'comment:post_comment' article.id %}"
                        method="POST"
                    >
                    {% csrf_token %}
                        <div class="form-group">
                            <label for="body">
                                <strong>
                                    我也要发言：
                                </strong>
                            </label>
                            <div>
                                {{ comment_form.media }}
                                {{ comment_form.body }}
                            </div>
                        </div>
                        <!-- 提交按钮 -->
                        <button type="submit" class="btn btn-primary ">发送</button>
                    </form>
                </div>
                <br>
            {% else %}
                <br>
                <h5 class="row justify-content-center">
                    请<a href="{% url 'userprofile:login' %}">登录</a>后回复
                </h5>
                <br>
            {% endif %}



            <!-- 显示评论 -->
            {% load mptt_tags %}
            <h4>共有{{ comments.count }}条评论</h4>
            <div class="row">
                <!-- 遍历树形结构 -->
                {% recursetree comments %}
                    {% with comment=node %}
                        <div class="{% if comment.reply_to %}
                                    offset-1 col-11
                                    {% else %}
                                    col-12
                                    {% endif %}"
                            id="comment_elem_{{ comment.id }}"
                        >
                            <hr>
                            <p>
                                <strong style="color: pink">
                                    {{ comment.user }}
                                </strong>

                                <!-- 显示被回复人 -->
                                {% if comment.reply_to %}
                                    <i class="far fa-arrow-alt-circle-right"
                                       style="color: cornflowerblue;"
                                    ></i>
                                    <strong style="color: pink">
                                        {{ comment.reply_to }}
                                    </strong>
                                {% endif %}

                            </p>
                            <div>{{ comment.body|safe }}</div>

                            <div>
                                <span style="color: gray">
                                    {{ comment.created|date:"Y-m-d H:i" }}
                                </span>

                                <!-- 加载 modal 的按钮 -->
                                {% if user.is_authenticated %}
                                    <button type="button"
                                            class="btn btn-light btn-sm text-muted"
                                            onclick="load_modal({{ article.id }}, {{ comment.id }})"
                                    >
                                        回复
                                    </button>
                                {% else %}
                                    <a class="btn btn-light btn-sm text-muted"
                                        href="{% url 'userprofile:login' %}"
                                    >
                                        回复
                                    </a>
                                {% endif %}
                            </div>

                            <!-- Modal -->
                            <div class="modal fade"
                                 id="comment_{{ comment.id }}"
                                 tabindex="-1"
                                 role="dialog"
                                 aria-labelledby="CommentModalCenter"
                                 aria-hidden="true"
                            >
                                <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
                                    <div class="modal-content" style="height: 480px">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalCenterTitle">回复 {{ comment.user }}：</h5>
                                        </div>
                                        <div class="modal-body" id="modal_body_{{ comment.id }}"></div>
                                    </div>
                                </div>
                            </div>

                            {% if not comment.is_leaf_node %}
                                <div class="children">
                                    {{ children }}
                                </div>
                            {% endif %}
                        </div>

                    {% endwith %}
                {% endrecursetree %}
            </div>
        </div>

        <!-- 目录 -->
        <div class="col-3 mt-4" id="sidebar" class="sidebar">
            <div class="sidebar__inner">
                <h4><strong>目录</strong></h4>
                <hr>
                <div>
                    {{ toc|safe }}
                </div>
            </div>
        </div>
    </div>
</div>

<!-- 粘性侧边栏样式 -->
<style>
    .sidebar{
        will-change: min-height;
    }

    .sidebar__inner{
        transform: translate(0, 0); /* For browsers don't support translate3d. */
        transform: translate3d(0, 0, 0);
        will-change: position, transform;
    }
</style>

<script>
    // 删除文章的函数
    function confirm_delete() {
        // 调用layer弹窗组件
        layer.open({
            // 弹窗标题
            title: "确认删除",
            // 正文
            content: "确认删除这篇文章吗？",
            // 点击确定按钮后调用的回调函数
            yes: function(index, layero) {
                // 指定应当前往的 url
                location.href='{% url "article:article_delete" article.id %}'
            },
        })
    }

    function confirm_safe_delete() {
        layer.open({
            title: "确认删除",
            content: "确认删除这篇文章吗？",
            yes: function(index, layero) {
                $('form#safe_delete button').click();
                layer.close(index);
            }
        })
    }
</script>
{% endblock content %}

{% block script %}

<!-- csrf token -->
<script src="{% static 'csrf.js' %}"></script>
<script>
    // 点赞功能主函数
    function validate_is_like(url, id, likes) {
        // 取出 LocalStorage 中的数据
        let storage = window.localStorage;
        const storage_str_data = storage.getItem("my_blog_data");
        let storage_json_data = JSON.parse(storage_str_data);
        // 若数据不存在，则创建空字典
        if (!storage_json_data) {
            storage_json_data = {}
        };
        // 检查当前文章是否已点赞。是则 status = true
        const status = check_status(storage_json_data, id);
        if (status) {
            layer.msg('已经点过赞了哟~');
            // 点过赞则立即退出函数
            return;
        } else {
            // 用 Jquery 找到点赞数量，并 +1
            $('span#likes_number').text(likes + 1).css('color', '#dc3545');
        }
        // 用 ajax 向后端发送 post 请求
        $.post(
            url,
            // post 只是为了做 csrf 校验，因此数据为空
            {},
            function(result) {
                if (result === 'success') {
                    // 尝试修改点赞数据
                    try {
                        storage_json_data[id] = true;
                    } catch (e) {
                        window.localStorage.clear();
                    };

                    const d = JSON.stringify(storage_json_data);
                    // 尝试存储点赞数据到 LocalStorage
                    try {
                        storage.setItem("my_blog_data", d);
                    } catch (e) {
                        // code 22 错误表示 LocalStorage 空间满了
                        if (e.code === 22) {
                            window.localStorage.clear();
                            storage.setItem("my_blog_data", d);
                        }
                    };
                } else {
                    layer.msg("与服务器通信失败..过一会儿再试试呗~");
                }

            }
        );
    };
    // 辅助点赞主函数，验证点赞状态
    function check_status(data, id) {
        // 尝试查询点赞状态
        try {
            if (id in data && data[id]) {
                return true;
            } else {
                return false;
            }
        } catch (e) {
            window.localStorage.clear();
            return false;
        };
    };
</script>

<!-- 粘性侧边栏 -->
<script src="{% static 'sticky_sidebar/jquery.sticky-sidebar.min.js' %}"></script>
<script type="text/javascript">
    $('#sidebar').stickySidebar({
        topSpacing: 20,
        bottomSpacing: 20,
    });
</script>

<!-- Ckeditor自适应 -->
<script>
    $(".django-ckeditor-widget").removeAttr('style');
</script>

<!-- 唤醒二级回复的 modal -->
<script>
    // 加载 modal
    function load_modal(article_id, comment_id) {
        let modal_body = '#modal_body_' + comment_id;
        let modal_id = '#comment_' + comment_id;

        // 加载编辑器
        if ($(modal_body).children().length === 0) {
            let content = '<iframe src="/comment/post-comment/' +
                article_id +
                '/' +
                comment_id +
                '" frameborder="0" style="width: 100%; height: 100%;"></iframe>';
            $(modal_body).append(content);
        };

        $(modal_id).modal('show');
    };

    // 处理二级回复
    function post_reply_and_show_it(new_comment_id) {
        let next_url = "{% url 'article:article_detail' article.id %}";
        // 去除 url 尾部 '/' 符号
        next_url = next_url.charAt(next_url.length - 1) == '/' ? next_url.slice(0, -1) : next_url;
        // 刷新并定位到锚点
        window.location.replace(next_url + "#comment_elem_" + new_comment_id);
    };
</script>
{% endblock script %}

templates/article/list.html
{% extends "base.html" %}
{% load staticfiles %}

<!-- 写入 base.html中定义的title-->
{% block title %}
    首页
{% endblock title %}

<!-- 写入base.html中定义的 content-->
{% block content %}
    <!-- 定义放置文章标题的div容器-->
    <div class="container">
        <!-- 修改，面包屑的href增加search参数 -->
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="{% url 'article:article_list' %}?search={{ search }}&column={{ column }}">最新</a>
                </li>
                <li class="breadcrumb-item">
                    <a href="{% url 'article:article_list' %}?order=total_views&search={{ search }}&column={{ column }}">最热</a>
                </li>
            </ol>
        </nav>

        <!--搜索栏-->
        <div class="row">
            <div class="col-auto mr-auto">
                <form class="form-inline">
                    <label class="sr-only">content</label>
                    <input type="text" class="form-control mb-2 mr-sm-2" name="search" placeholder="搜索文章..." required>
                </form>
            </div>
        </div>

        <!--搜索提示语-->
        {% if search %}
            {% if articles %}
                <h4><span style="color: red">"{{ search }}"</span>的搜索结果如下：</h4>
                <hr>
            {% else %}
                <h4>暂无<span style="color: red">"{{ search }}"</span>有关的文章。</h4>
                <hr>
            {% endif %}
        {% endif %}

        <!-- 列表循环-->
        <div class="row mt-2">
            {% for article in articles %}
                <!-- 标题图-->
                {% if article.avatar %}
                    <div class="col-3">
                        <img src="{{ article.avatar.url }}" alt="avatar" style="max-width: 100%;border-radius: 20px">
                    </div>
                {% endif %}

                <div class="col">
                    <!-- 栏目-->
                    {% if article.column %}
                        <a role="button" href="{% url 'article:article_list' %}?column={{ article.column.id }}"
                           class="btn btn-sm mb-2 btn-success">
                            {{ article.column }}
                        </a>
                    {% endif %}
                    <!-- 标签-->
                    <span>
                        {% for tag in article.tags.all %}
                            <a class="badge badge-secondary"
                               href="{% url 'article:article_list' %}?tag={{ tag }}">{{ tag }}</a>
                        {% endfor %}
                    </span>

                    <!-- 标题-->
                    <h4>
                        <b>
                            <a href="{% url 'article:article_detail' article.id %}" style="color: black">
                                {{ article.title }}
                            </a>
                        </b>
                    </h4>
                    <!-- 摘要-->
                    <div>
                        <p style="color: gray;">
                            {{ article.body | slice:'100' }}...
                        </p>
                    </div>
                    <!-- 注脚-->
                    <p>
                        <!-- 附加信息,增加了图标-->
                        <span>
                            <i class="fas fa-eye" style="color:lightskyblue"></i>
                        {{ article.total_views }}&nbsp;&nbsp;&nbsp;&nbsp;
                    </span>
                        <span>
                            <i class="fas fa-comments" style="color:yellowgreen;"></i>
                            <!-- 修改文评论的计数 -->
                            {{ article.comments.count}}&nbsp;&nbsp;&nbsp;&nbsp;

                        </span>
                        <span>
                            <i class="fas fa-clock" style="color: pink;"></i>
                            {{ article.created | date:'Y-m-d' }}&nbsp;&nbsp;
                    </span>
                    </p>
                </div>
                <hr style="width:100%;"/>

            {% endfor %}
        </div>
        <!-- 页码导航-->
        <div class="pagination row">
            <div class="m-auto">
            <span class="step-links">
                <!-- 如果不是第一页，则显示上翻页按钮-->
                {% if articles.has_previous %}
                    <a href="?page=1&order={{ order }}&search={{ search }}&column={{ column }}&tag={{ tag }}"
                       class="btn btn-success">1</a>
                    <a href="?page={{ articles.previous_page_number }}&order={{ order }}&search={{ search }}&column={{ column }}&tag={{ tag }}"
                       class="btn btn-secondary">...</a>
                {% endif %}
                <!-- 当前页面-->
                <span class="current btn btn-danger btn-lg">{{ articles.number }}</span>
                <!-- 如果不是末页，则显示下翻按钮-->
                {% if articles.has_next %}
                    <a href="?page={{ articles.next_page_number }}&order={{ order }}&search={{ search }}&column={{ column }}&tag={{ tag }}"
                       class="btn btn-secondary">{{ articles.paginator.num_pages }}</a>
                    <a href="?page={{ articles.paginator.num_pages }}&order={{ order }}&search={{ search }}&column={{ column }}&tag={{ tag }}"
                       class="btn btn-success">
                        {{ articles.paginator.num_pages }}&raquo;
                    </a>
                {% endif %}
            </span>

            </div>

        </div>
    </div>
{% endblock %}